config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs do
    member do
      get :assign
    end
  end

  resources :boats do
    member do
      get :jobs
      post :job_add
      post :job_remove
      patch :start

    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # validate name is unique
  validates :name, :uniqueness => true

  # a boat can be in many jobs, a job can have many boats
  has_and_belongs_to_many :jobs

	belongs_to :user, required: false
	has_many :locations

  #  Check if boat is alredy assigned to a specific job
  def assigned_in?(job)
    self.jobs.include?(job)
  end
  # check the jobs the boat is not assigned to
  def unassigned_jobs
    Job.all - self.jobs
  end

end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :locations, required: false

	# a boat can be in many jobs, a job can have many boats
	has_and_belongs_to_many :boats, required: false

	validates :description, presence: true, length: {minimum: 50}
  validates :cost, numericality: { :greater_than => 1000, :less_than_or_equal_to => 999999999}

end

app/models/location.rb
class Location < ApplicationRecord
	has_many :boats
	has_many :jobs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :boats
	has_many :jobs, through: :boats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_boat, only: [:show, :edit, :update, :destroy, :start]


  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # List jobs a boat is in:
  def jobs
    @boat = Boat.find(params[:id])
    @boats = @boat.jobs
  end

  # GET /boats/new
  def new
    @boat = current_user.boats.build
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  def create
    @boat = current_user.boats.build(boat_params)
    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def job_add
    # convert ids from routing to objects
    @boat = Boat.find(params[:id])
    @job = Job.find(params[:job])

    unless @boat.assigned_in?(@job)
      #adds the job to list of jobs for current boat
      @boat.jobs << @job
      flash[:notice] = 'Job was assigned!'
    else
      flash[:error] = 'FAILED TO ASSIGN'
    end

    redirect_to action: "jobs", id: @boat
  end

  # Removing a boat from a job_id
  def job_remove
    @boat = Boat.find(params[:id])
    job_ids = params[:jobs]
    if job_ids.any?

      job_ids.each do |course_id|
        job = Job.find(job_ids)
        if @boat.assigned_in?(job)
          logger.info "Removing boat from job #{job.id}"
          @boat.jobs.delete(job)
          flash[:notice] = 'Job was deleted'
        end
      end
    end

    redirect_to action: "Jobs", id: @boat
  end




  def start
    @boat = Boat.find(params[:id])
    @boat.update(started_at: Time.zone.now)
  end





  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # taks boat id and single job id and adds the boat to that job

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :containers, :location, :image)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_job, only: [:show, :update, :destroy, :edit]
	def index
		@jobs = Job.all
	end

  def show
  end

  def new
  @job = Job.new
  end

	def edit
		# @job = Job.find(params[:id])
	end

  def create
		@job = Job.new(job_params)
		@job.user = current_user
		respond_to do |format|
			if @job.save
				format.html { redirect_to @job, notice: 'Job was successfully created.' }
      else
        format.html { render :new }
			end
		end
  end

  def update
		respond_to do |format|
			if @job.update(job_params)
				format.html {redirect_to @job, notice: 'Job was successfully updated.'}
				format.json { render :show, status: :ok, location: @job }
			else
				format.html { render :edit }
			end
    end
  end

  def destroy
		@job.destroy if @job.id == session[:job_id]
		session[:job_id] = nil
		respond_to do |format|
      format.html { redirect_to boats }
		end
  end


	# Provide a list of the boats  assinged to the job
	def assign
		@job = Job.find(params[:id])
	end

  private
		def set_job
      @job = Job.find(params[:id])
		end

    def job_params
       params.require(:job).permit(:name, :description, :origin, :destination, :cost, :containers, :boat)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to boats,
      notice: "Wecome to the site!"
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit( :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/boatw_jobs_helper.rb
module BoatwJobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navigation.html.erb
<p>
<%= link_to "Boats", boats_path %> | <%= link_to "Jobs", jobs_path %>
</p> <hr>

app/views/boats/_form.html.erb
<%= form_with(model: boat, local: true)do |form| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :boat_name %>
  </div>

  <div class="field">
    <%= form.label :containers %>
    <%= form.number_field :containers, id: :boat_containers %>
  </div>

  <div class="field" >
    <%= form.label :Locat %>
    <%= form.collection_select :location_id, Location.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :boat_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<div id="h2container"><h2>Editing Boat</h2></div>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<div id="h2container"><h2>Boats</h2></div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Containers</th>
      <th>Location</th>
      <th>Job Count</th>
      <th>Boat Picture</th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.containers %></td>
        <td><%= boat.location %></td>
        <td><%= boat.jobs.count %></td>
        <td><%= image_tag boat.image.url(:medium)  %></td>


        <td><%= link_to 'Details', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td> <br>

        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>
<div id="new"><%= link_to 'New Boat', new_boat_path %></div>

app/views/boats/job_add.js.erb
$('#ass').hid()

app/views/boats/jobs.html.erb
<h1><%= @boat.name %>'s Job</h1>

<% if @boat.jobs.count > 0 %>
  <%= form_tag(job_remove_boat_path(@boat)) do %>
  <table>
    <thead>
      <tr>
        <th>Job</th>
        <th>Remove?</th>
      </tr>
    </thead>

    <tbody>

      <% for job in @boat.jobs do %>
        <tr>
          <td><%= job.origin %></td>
          <td><%= job.destination %></td>
          <td><%= check_box_tag "jobs[]", job.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= submit_tag 'Remove checked Jobs' %>
  <% end %>
<% else %>
  <p>Not assinged to a job</p>
<% end %>

  <h2>Assign Job</h2>

  <% if @boat.jobs.count < Job.count then %>
    <%= form_tag(job_add_boat_path(@boat)) do %>
      <%= select_tag(:job, options_from_collection_for_select(@boat.unassigned_jobs, :id, :name)) %>
      <%= submit_tag 'Assign', remote: true %>
    <% end %>
  <% else %>
    <p><%= @boat.name %> CANNOT BE ASSIGNED .</p>
  <% end %>



  <p><%=link_to "Back", @boat %></p>

app/views/boats/new.html.erb
<div id="h2container"><h2>New Boat</h2></div>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<div id="boatshow">
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @boat.image.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>

<p>
  <strong>Containers:</strong>
  <%= @boat.containers %>
</p>

<p>
  <strong>Location:</strong>
  <%= @boat.location %>
</p>

<p>
  <strong>Jobs</strong>
  <% if !@boat.jobs.empty?  %>
    <%= @boat.jobs.collect {|c| link_to(c.name, c)}.join(", ").html_safe %>
  <% else %>
      Not Assigned to a job.
  <% end %>
</p>

<p>
  <strong>Time Trip Started:</strong>
  <span id = "started-at">
  <%= @boat.started_at %></span>
</p>

<%= link_to "Start Trip", start_boat_path(@boat), method: :patch, remote: true %>|

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Jobs', jobs_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>
</div>

app/views/boats/start.js.erb
$("#started-at").text("<%= @boat.started_at %>")

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name, id: :job_name %>
  </div>


<div id="description"
  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :description, id: :job_description %>

  </div>

  <div class="field">
    <%= form.label :Containers %>
    <%= form.number_field :containers, id: :job_containers %>
  </div>

<div id="toandfrom">
  <div class="field" >
    <%= form.label :Origin %>
    <%= form.collection_select :origin, Location.all, :name, :name %>
  </div>

  <div class="field" >
    <%= form.label :Destination %>
    <%= form.collection_select :destination, Location.all, :name, :name %>
  </div>
</div>

  <div class="field" >
    <%= form.label :Cost %>
    <%= form.number_field :cost %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/assign.html.erb
<h1>Assign For</h1>

<% if @job.boats.count > 0 %>
  <table class="table">
    <tr>
      <th>Boat</th>
    </tr>

  <tbody>
    <% @job.boats.each do |boat| %>
    <tr>
      <td><%=link_to boat.name, boat%></td>
    </tr>
  <% end %>
  </tbody>
  <% else %>
    <p>No boat are Assigned.</p>
  <% end %>
  </table>

  <p><%link_to "Back", @job %></p>

app/views/jobs/edit.html.erb
<div id="h2container"><h2>Editing Jobs</h2></div>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/form.html.erb
<%= form_with(model: jobs, local: true) do |form| %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :boat_name %>
  </div>

  <div class="field">
    <%= form.label :containers %>
    <%= form.number_field :containers, id: :boat_containers %>
  </div>

  <div class="field" >
    <%= form.label :Origin %>
    <%= form.collection_select :location_id, Location.all, :id, :name %>
  </div>

  <div class="field" >
    <%= form.label :Destination %>
    <%= form.collection_select :location_id, Location.all, :id, :name %>
  </div>

  <div class="field" >
    <%= form.label :cost %>
    <%= form.number_field :cost %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<div id="h2container">
  <h2>Jobs</h2>
</div>

<% @jobs.each do |job| %>
  <%= job.id %>.

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Containers</th>
        <th>Cost</th>


      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.description %></td>
        <td><%= job.origin %></td>
        <td><%= job.destination %></td>
        <td><%= job.containers %></td>
        <td><%= job.cost %></td>
        <td><%= link_to 'Show', job %></td>


        <%= form_tag(model: job, local: true) do |form| %>
        <td><%= form.collection_select :origin, Location.all, :name, :name %></td>
        <td><%= link_to 'Assign Boat', @boat %></td>
        <% end %>

      </tr>
    </tbody>
  </table>

<% end  %>

<center><%= link_to 'New Job', new_job_path %></center>

app/views/jobs/new.html.erb
<div id="h2container"><h2>New Job</h2></div>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<div class="table1">

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @job.origin%>
</p>

<p>
  <strong>Destination:</strong>
  <%= @job.destination %>
</p>

<p>
	<strong>Containers:</strong>
	<%= @job.containers %>
</p>

<p>
	<strong>Cost:</strong>
	<%= @job.cost %>
</p>

<p>

	<strong>Boat Assigned:</strong>
	<%= @job.boats %>

	<strong>Boat:</strong>
	<%= @job.boats.name %>
</p>


</div>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to "Assign", assign_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipped</title>
    <%= csrf_meta_tags %>

    <style>
    @import url('https://fonts.googleapis.com/css?family=Merriweather');
    @import url('https://fonts.googleapis.com/css?family=Heebo');
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:900i');

    </style>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="usernav"><% if user_signed_in? %>
    <li><%= link_to 'Sign Out', { :action=>"destroy", :controller=>"devise/sessions" }, method: :delete %></li>
    <% else %>
    <li><%= link_to "Register", new_user_registration_path %></li>
    <li><%= link_to "Log In", new_user_session_path %></li></ul>
    <% end %>
  </div>

    <div class="header_container"><h1>Rails: Shipped</h1></div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<div class="mainnav">
  <%= link_to "Jobs", jobs_path %>
  <%= link_to "Boats", boats_path %>
</div>


<%= yield %>
=======
</ul>
</nav>
   
            
  </body>
</html>